package io.titan.introspect;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

import java.util.List;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

/**
 * GAP G-6/G-7 corpus: container-backed DDL introspection handles everything the regex parser
 * used to drop silently — table options ({@code ENGINE=InnoDB}), {@code CREATE OR REPLACE VIEW},
 * FK referential actions, {@code ALTER TABLE ... ADD CONSTRAINT}, PostgreSQL enum types,
 * precision/scale, and {@code timestamptz} — because the DDL is applied to a real scratch
 * database and introspected through the JDBC path.
 */
// Docker-dependent (Testcontainers); runs via the integrationTest task, excluded from plain test (plan 4.5).
@org.junit.jupiter.api.Tag("docker")
class DdlContainerIntrospectorIT {

    @BeforeAll
    static void requiresDocker() {
        assumeTrue(DdlContainerIntrospector.dockerAvailable(), "Docker is required for container-backed introspection ITs");
    }

    @Test
    void postgresDdlCorpusThatTheRegexParserCannotRepresent() throws Exception {
        String ddl = """
                CREATE SEQUENCE account_seq START 100;

                CREATE TYPE account_status AS ENUM ('ACTIVE', 'SUSPENDED', 'CLOSED');

                CREATE TABLE customers (
                  id bigint GENERATED BY DEFAULT AS IDENTITY,
                  email character varying(255) NOT NULL,
                  CONSTRAINT customers_pkey PRIMARY KEY (id),
                  CONSTRAINT customers_email_key UNIQUE (email)
                );

                CREATE TABLE accounts (
                  id bigint NOT NULL DEFAULT nextval('account_seq'),
                  customer_id bigint NOT NULL,
                  status account_status NOT NULL DEFAULT 'ACTIVE',
                  balance numeric(12,2) NOT NULL DEFAULT 0,
                  opened_at timestamptz NOT NULL DEFAULT now(),
                  CONSTRAINT accounts_pkey PRIMARY KEY (id),
                  CONSTRAINT accounts_customer_fk FOREIGN KEY (customer_id)
                      REFERENCES customers (id) ON DELETE CASCADE
                );

                CREATE TABLE audit_events (
                  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                  account_id bigint
                );

                ALTER TABLE audit_events
                  ADD CONSTRAINT audit_events_account_fk FOREIGN KEY (account_id) REFERENCES accounts (id);

                CREATE OR REPLACE VIEW active_accounts AS
                SELECT a.id, a.balance, c.email
                FROM accounts a JOIN customers c ON c.id = a.customer_id
                WHERE a.status = 'ACTIVE';
                """;

        SchemaModel model = new DdlContainerIntrospector().introspect(
                List.of(new DdlContainerIntrospector.DdlSource("corpus-pg.sql", ddl)),
                Dialect.POSTGRESQL,
                List.of("public"),
                DdlContainerIntrospector.driverManagerConnections());

        // Enum type introspected as a real type with ordered values.
        assertEquals(1, model.enumTypes().size());
        assertEquals("account_status", model.enumTypes().getFirst().name());
        assertEquals(List.of("ACTIVE", "SUSPENDED", "CLOSED"), model.enumTypes().getFirst().values());

        var accounts = model.tables().stream().filter(t -> t.name().equals("accounts")).findFirst().orElseThrow();

        var status = accounts.columns().stream().filter(c -> c.name().equals("status")).findFirst().orElseThrow();
        assertEquals("enum", status.sqlType());
        assertEquals("account_status", status.enumTypeName());
        assertEquals(List.of("ACTIVE", "SUSPENDED", "CLOSED"), status.enumValues());

        // Precision/scale survive (the regex parser used to drop them entirely).
        var balance = accounts.columns().stream().filter(c -> c.name().equals("balance")).findFirst().orElseThrow();
        assertEquals(12, balance.precision());
        assertEquals(2, balance.scale());

        // Time-zone fidelity (the regex parser used to lose timestamptz).
        var openedAt = accounts.columns().stream().filter(c -> c.name().equals("opened_at")).findFirst().orElseThrow();
        assertEquals("timestamptz", openedAt.sqlType());

        // Sequence-backed default is recognized as auto-increment.
        assertTrue(accounts.columns().stream().filter(c -> c.name().equals("id")).findFirst().orElseThrow().autoIncrement());

        // FK with ON DELETE was applied, not dropped.
        assertTrue(accounts.foreignKeys().stream().anyMatch(fk -> fk.name().equals("accounts_customer_fk")
                && fk.referencedTable().equals("customers")
                && fk.columns().equals(List.of("customer_id"))));

        // ALTER TABLE ... ADD CONSTRAINT lands in the model.
        var auditEvents = model.tables().stream().filter(t -> t.name().equals("audit_events")).findFirst().orElseThrow();
        assertTrue(auditEvents.foreignKeys().stream().anyMatch(fk -> fk.name().equals("audit_events_account_fk")
                && fk.referencedTable().equals("accounts")));

        // CREATE OR REPLACE VIEW exists, with typed columns (the parser leaves views untyped).
        var view = model.views().stream().filter(v -> v.name().equals("active_accounts")).findFirst().orElseThrow();
        assertEquals(3, view.columns().size());
        var viewId = view.columns().stream().filter(c -> c.name().equals("id")).findFirst().orElseThrow();
        assertEquals("bigint", viewId.sqlType());
        var viewEmail = view.columns().stream().filter(c -> c.name().equals("email")).findFirst().orElseThrow();
        assertNotEquals("unknown", viewEmail.sqlType());
        assertEquals("varchar", viewEmail.sqlType());
    }

    @Test
    void mysqlDdlCorpusWithEngineOptionsEnumsAndReferentialActions() throws Exception {
        String ddl = """
                CREATE TABLE plans (
                  id INT AUTO_INCREMENT,
                  code VARCHAR(32) NOT NULL,
                  PRIMARY KEY (id),
                  UNIQUE KEY uq_plans_code (code)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

                CREATE TABLE accounts (
                  id BIGINT NOT NULL AUTO_INCREMENT,
                  plan_id INT,
                  status ENUM('ACTIVE','SUSPENDED') NOT NULL DEFAULT 'ACTIVE',
                  balance DECIMAL(10,2) NOT NULL,
                  created_at DATETIME NOT NULL,
                  PRIMARY KEY (id),
                  CONSTRAINT fk_accounts_plan FOREIGN KEY (plan_id) REFERENCES plans (id) ON DELETE SET NULL
                ) ENGINE=InnoDB;

                ALTER TABLE accounts ADD CONSTRAINT uq_accounts_created UNIQUE (created_at);

                CREATE OR REPLACE VIEW active_accounts AS
                SELECT id, balance FROM accounts WHERE status = 'ACTIVE';
                """;

        SchemaModel model = new DdlContainerIntrospector().introspect(
                List.of(new DdlContainerIntrospector.DdlSource("corpus-mysql.sql", ddl)),
                Dialect.MYSQL,
                List.of("titan"),
                DdlContainerIntrospector.driverManagerConnections());

        var accounts = model.tables().stream().filter(t -> t.name().equals("accounts")).findFirst().orElseThrow();

        // ENGINE=InnoDB tables introspect normally instead of being dropped wholesale.
        assertEquals(2, model.tables().size());

        // MySQL enum names are synthesized per column (G-8), never the raw enum('...') string.
        var status = accounts.columns().stream().filter(c -> c.name().equals("status")).findFirst().orElseThrow();
        assertEquals("enum", status.sqlType());
        assertEquals("accounts_status_enum", status.enumTypeName());
        assertEquals(List.of("ACTIVE", "SUSPENDED"), status.enumValues());
        assertTrue(model.enumTypes().stream().anyMatch(e -> e.name().equals("accounts_status_enum")));

        var balance = accounts.columns().stream().filter(c -> c.name().equals("balance")).findFirst().orElseThrow();
        assertEquals(10, balance.precision());
        assertEquals(2, balance.scale());

        assertTrue(accounts.foreignKeys().stream().anyMatch(fk -> fk.name().equals("fk_accounts_plan")
                && fk.referencedTable().equals("plans")));

        // ALTER TABLE ... ADD CONSTRAINT lands in the model.
        assertTrue(accounts.constraints().stream().anyMatch(c -> c.name().equals("uq_accounts_created")
                && c.type() == SchemaModel.ConstraintType.UNIQUE));

        var view = model.views().stream().filter(v -> v.name().equals("active_accounts")).findFirst().orElseThrow();
        assertEquals(2, view.columns().size());
        assertEquals("bigint", view.columns().getFirst().sqlType());
    }
}
