package io.titan.introspect;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

import java.util.List;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

/**
 * GAP G-7: for the DDL subset the fallback parser genuinely supports, parser mode and
 * container mode (scratch database + JDBC introspection) must produce <em>identical</em>
 * {@link SchemaModel}s — same types, precision/scale, lengths, nullability, constraint and
 * index naming/ordering. Anything outside this subset makes the parser fail loudly instead of
 * diverging silently.
 */
// Docker-dependent (Testcontainers); runs via the integrationTest task, excluded from plain test (plan 4.5).
@org.junit.jupiter.api.Tag("docker")
class DdlModeEquivalenceIT {

    @BeforeAll
    static void requiresDocker() {
        assumeTrue(DdlContainerIntrospector.dockerAvailable(), "Docker is required for container-backed introspection ITs");
    }

    @Test
    void postgresParserAndContainerModesProduceIdenticalSchemaModels() throws Exception {
        String ddl = """
                CREATE TABLE customers (
                  id bigint GENERATED BY DEFAULT AS IDENTITY,
                  email character varying(255) NOT NULL,
                  balance numeric(12,2),
                  note text,
                  created_at timestamp without time zone NOT NULL,
                  CONSTRAINT customers_pkey PRIMARY KEY (id),
                  CONSTRAINT customers_email_key UNIQUE (email)
                );

                CREATE TABLE orders (
                  id bigint NOT NULL,
                  customer_id bigint NOT NULL,
                  qty integer NOT NULL,
                  CONSTRAINT orders_pkey PRIMARY KEY (id),
                  CONSTRAINT orders_customer_fk FOREIGN KEY (customer_id) REFERENCES customers (id)
                );

                CREATE INDEX idx_orders_customer ON orders (customer_id);
                """;

        SchemaModel parsed = new DdlSchemaParser().parse(ddl, Dialect.POSTGRESQL, "public");
        SchemaModel containerIntrospected = new DdlContainerIntrospector().introspect(
                List.of(new DdlContainerIntrospector.DdlSource("equivalence-pg.sql", ddl)),
                Dialect.POSTGRESQL,
                List.of("public"),
                DdlContainerIntrospector.driverManagerConnections());

        assertEquals(containerIntrospected, parsed,
                "parser mode must produce the exact SchemaModel the scratch-container JDBC path produces");
    }

    @Test
    void mysqlParserAndContainerModesProduceIdenticalSchemaModels() throws Exception {
        String ddl = """
                CREATE TABLE plans (
                  id INT NOT NULL AUTO_INCREMENT,
                  code VARCHAR(32) NOT NULL,
                  PRIMARY KEY (id),
                  UNIQUE KEY uq_plans_code (code)
                );

                CREATE TABLE accounts (
                  id BIGINT NOT NULL,
                  plan_id INT,
                  status ENUM('ACTIVE','SUSPENDED') NOT NULL,
                  balance DECIMAL(10,2) NOT NULL,
                  created_at DATETIME NOT NULL,
                  PRIMARY KEY (id),
                  CONSTRAINT fk_accounts_plan FOREIGN KEY (plan_id) REFERENCES plans (id)
                );
                """;

        SchemaModel parsed = new DdlSchemaParser().parse(ddl, Dialect.MYSQL, "titan");
        SchemaModel containerIntrospected = new DdlContainerIntrospector().introspect(
                List.of(new DdlContainerIntrospector.DdlSource("equivalence-mysql.sql", ddl)),
                Dialect.MYSQL,
                List.of("titan"),
                DdlContainerIntrospector.driverManagerConnections());

        assertEquals(containerIntrospected, parsed,
                "parser mode must produce the exact SchemaModel the scratch-container JDBC path produces");
    }
}
