plugins {
    id("titan.library-conventions")
}

description = "Dependency-free Java DSL for typed SQL construction and rendering."

dependencies {
    testImplementation(libs.archunit.junit5)
}

// ---------------------------------------------------------------------------
// Arity-ladder source generation (audit D-5, plan 3.3, post-loop policy Option A).
//
// SelectBuilder1..10, Tuple1..10 and the 3..10-ary consumer interfaces are generated from one
// template at build time instead of being hand-maintained (git history shows four "fix all ten
// classes" drift commits). The cap stays at 10 by policy (docs/post-loop-design-considerations.md);
// raising it must be an explicit design decision, not an edit here.
//
// This is build-time-only tooling: titan-dsl stays dependency-free at runtime, and the generated
// classes are byte-for-byte semantically equivalent to the previous hand-written ones (the
// existing DSL test suite is the contract).
// ---------------------------------------------------------------------------

/** Typed projection arity cap. Policy-fixed at 10; see docs/post-loop-design-considerations.md. */
val arityCap = 10

/** Names of the n-ary consumer functional interfaces, indexed by arity (3..10). */
val consumerNames = mapOf(
    3 to "TriConsumer",
    4 to "QuadConsumer",
    5 to "QuintConsumer",
    6 to "HexConsumer",
    7 to "HeptConsumer",
    8 to "OctConsumer",
    9 to "EnneaConsumer",
    10 to "DecaConsumer",
)

fun typeParams(n: Int): String = (1..n).joinToString(", ") { "T$it" }

fun generatedHeader(): String =
    "// Generated by the titan-dsl arity source generator (titan-dsl/build.gradle.kts, audit D-5).\n" +
        "// SPDX-License-Identifier: GPL-3.0-only\n" +
        "// Do not edit: regenerate via ./gradlew generateAritySources. Arity cap is policy-fixed\n" +
        "// at 10 (docs/post-loop-design-considerations.md).\n"

fun tupleSource(n: Int): String {
    val components = (1..n).joinToString(",\n        ") { "T$it value$it" }
    return buildString {
        append("package titan.dsl;\n\n")
        append(generatedHeader())
        append("public record Tuple$n<${typeParams(n)}>(\n        $components) {\n}\n")
    }
}

fun consumerSource(n: Int): String {
    val name = consumerNames.getValue(n)
    val params = (1..n).joinToString(", ") { "T$it value$it" }
    return buildString {
        append("package titan.dsl;\n\n")
        append(generatedHeader())
        append("@FunctionalInterface\n")
        append("public interface $name<${typeParams(n)}> {\n")
        append("    void accept($params);\n")
        append("}\n")
    }
}

fun selectBuilderSource(n: Int): String {
    val generics = typeParams(n)
    val self = "SelectBuilder$n<$generics>"
    val constructorParams = (1..n).joinToString(",\n            ") { "Column<T$it> column$it" }
    val constructorArgs = (1..n).joinToString(", ") { "column$it" }

    fun fluentOverride(signature: String, call: String): String =
        "    @Override\n    public $self $signature {\n        super.$call;\n        return this;\n    }\n"

    return buildString {
        append("package titan.dsl;\n\n")
        append(generatedHeader())
        append("public final class SelectBuilder$n<$generics> extends SelectBuilder {\n\n")
        append("    SelectBuilder$n(\n            $constructorParams) {\n")
        append("        super($constructorArgs);\n")
        append("    }\n\n")
        append("    SelectBuilder$n(SqlDialect dialect,\n            $constructorParams) {\n")
        append("        super(dialect, $constructorArgs);\n")
        append("    }\n\n")
        append("    SelectBuilder$n(SqlDialect dialect,\n            QueryFilters filters,\n            $constructorParams) {\n")
        append("        super(dialect, filters, $constructorArgs);\n")
        append("    }\n\n")
        append(
            listOf(
                "from(TableLike<?> table)" to "from(table)",
                "distinct()" to "distinct()",
                "where(Condition condition)" to "where(condition)",
                "groupBy(Column<?>... columns)" to "groupBy(columns)",
                "groupBy(GroupByExpression... expressions)" to "groupBy(expressions)",
                "having(Condition condition)" to "having(condition)",
                "orderBy(SortField... sortFields)" to "orderBy(sortFields)",
                "limit(int limit)" to "limit(limit)",
                "offset(int offset)" to "offset(offset)",
                "forUpdate()" to "forUpdate()",
                "forShare()" to "forShare()",
                "skipLocked()" to "skipLocked()",
                "noWait()" to "noWait()",
                "union(SelectBuilder other)" to "union(other)",
                "unionAll(SelectBuilder other)" to "unionAll(other)",
                "intersect(SelectBuilder other)" to "intersect(other)",
                "except(SelectBuilder other)" to "except(other)",
            ).joinToString("\n") { (signature, call) -> fluentOverride(signature, call) }
        )
        append("\n")
        append("    public Class<Tuple$n> tupleType() {\n")
        append("        return Tuple$n.class;\n")
        append("    }\n\n")
        if (n == 1) {
            // Read-into-local scalar terminal (Phase A4 / G2): a single-column projection's value
            // typed to the column's Java type T1, so it can be bound to a typed routine local and
            // branched on, e.g. `int v = select(T.COL).from(T).where(...).fetchScalar(); if (v...)`.
            // The transpiler recognizes this terminal and lowers the chain to SELECT <col> INTO
            // <local> on both dialects (no row => the local is left NULL). It is the typed sibling
            // of the SQL-skeleton fetchOne()/fetch() terminals (which return String). Only arity 1
            // exposes it because a scalar local binds exactly one column.
            append("    public T1 fetchScalar() {\n")
            append("        // The transpiler reconstructs the SQL from the parsed chain, never from a\n")
            append("        // runtime call; a value here only matters for a direct (non-transpiled)\n")
            append("        // JdbcExecutor invocation, which overrides execution.\n")
            append("        return null;\n")
            append("    }\n\n")
        }
        append("    public String forEach(java.util.function.Consumer<Tuple$n<$generics>> rowConsumer) {\n")
        append("        java.util.Objects.requireNonNull(rowConsumer, \"rowConsumer\");\n")
        append("        return super.forEach();\n")
        append("    }\n")
        append("}\n")
    }
}

val aritySourcesDir = layout.buildDirectory.dir("generated/sources/titan-dsl/java/main")

val generateAritySources = tasks.register("generateAritySources") {
    description = "Generates SelectBuilder1..$arityCap, Tuple1..$arityCap and the n-ary consumer interfaces from one template (audit D-5)."
    group = "build"
    // The template lives in this build script; bump when the template changes so the task re-runs.
    inputs.property("arityCap", arityCap)
    inputs.property("templateVersion", 6)
    outputs.dir(aritySourcesDir)
    doLast {
        val packageDir = aritySourcesDir.get().asFile.resolve("titan/dsl")
        packageDir.deleteRecursively()
        packageDir.mkdirs()
        for (n in 1..arityCap) {
            packageDir.resolve("Tuple$n.java").writeText(tupleSource(n))
            packageDir.resolve("SelectBuilder$n.java").writeText(selectBuilderSource(n))
        }
        for (n in consumerNames.keys) {
            packageDir.resolve("${consumerNames.getValue(n)}.java").writeText(consumerSource(n))
        }
    }
}

sourceSets {
    main {
        java {
            srcDir(generateAritySources)
        }
    }
}
