package io.titan.gradle;

import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

import io.titan.introspect.DdlContainerIntrospector;
import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * GAP G-6/G-7 wiring: in the default DDL mode the introspect task applies the DDL files to a
 * scratch Testcontainers database and introspects via JDBC, so DDL constructs the regex parser
 * cannot represent (PostgreSQL enum types, ALTER TABLE) land in schema.json.
 */
// Docker-dependent (Testcontainers); runs via the integrationTest task, excluded from plain test (plan 4.5).
@org.junit.jupiter.api.Tag("docker")
class TitanIntrospectTaskContainerModeIT {

    @TempDir
    Path tempDir;

    @BeforeAll
    static void requiresDocker() {
        assumeTrue(DdlContainerIntrospector.dockerAvailable(), "Docker is required for container-backed introspection ITs");
    }

    @Test
    void containerModeIntrospectsDdlThatTheFallbackParserRejects() throws Exception {
        Project project = ProjectBuilder.builder().withProjectDir(tempDir.toFile()).build();
        TitanIntrospectTask task = project.getTasks().create("titanIntrospect", TitanIntrospectTask.class);

        Path ddl = tempDir.resolve("schema.sql");
        Files.writeString(ddl, """
                CREATE TYPE account_status AS ENUM ('ACTIVE', 'SUSPENDED');

                CREATE TABLE accounts (
                  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  status account_status NOT NULL,
                  opened_at timestamptz NOT NULL
                );

                ALTER TABLE accounts ADD CONSTRAINT accounts_opened_key UNIQUE (opened_at);
                """, StandardCharsets.UTF_8);

        task.getDdlFiles().from(ddl.toFile());
        // ddlMode left unset: container is the default behavior for DDL sources.
        task.getDialect().set("postgresql");
        task.getSchemas().set(java.util.List.of("public"));
        Path schemaJson = tempDir.resolve("titan/schema.json");
        task.getSchemaJsonFile().set(schemaJson.toFile());
        // titanJdbc deliberately left empty: TitanJdbcConnections falls back to DriverManager,
        // which sees the PostgreSQL driver on this test's classpath.

        task.run();

        String json = Files.readString(schemaJson, StandardCharsets.UTF_8);
        assertTrue(json.contains("\"account_status\""), "enum type must reach schema.json, was:\n" + json);
        assertTrue(json.contains("\"SUSPENDED\""), json);
        assertTrue(json.contains("timestamptz"), "time-zone fidelity must reach schema.json");
        assertTrue(json.contains("accounts_opened_key"), "ALTER TABLE ADD CONSTRAINT must reach schema.json");
    }
}
