package io.titan.gradle;

import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class TitanGenerateTaskTest {

    @TempDir
    Path tempDir;

    private TitanGenerateTask ddlBackedTask(Path outputDir) throws Exception {
        Project project = ProjectBuilder.builder().withProjectDir(tempDir.toFile()).build();
        TitanGenerateTask task = project.getTasks().create("titanGenerate", TitanGenerateTask.class);

        Path ddl = tempDir.resolve("schema.sql");
        Files.writeString(ddl, """
                CREATE TABLE public.accounts (
                  id INTEGER NOT NULL,
                  email VARCHAR(255),
                  PRIMARY KEY (id)
                );
                """, StandardCharsets.UTF_8);

        task.getDdlFiles().from(ddl.toFile());
        // Unit tests stay hermetic (no Docker): use the documented no-Docker fallback parser
        // instead of the default scratch-container mode.
        task.getDdlMode().set("parser");
        task.getDialect().set("postgresql");
        task.getSchemas().set(java.util.List.of("public"));
        task.getTargetPackage().set("com.example.generated");
        task.getOutputDir().set(outputDir.toFile());
        return task;
    }

    // GAP S8 regression: the homegrown fingerprint used to early-return and leave a manually
    // deleted output missing forever. The action must regenerate everything whenever it runs;
    // skipping reruns is exclusively Gradle's up-to-date check now.
    @Test
    void regeneratesDeletedOutputsOnRerun() throws Exception {
        Path outputDir = tempDir.resolve("generated");
        TitanGenerateTask task = ddlBackedTask(outputDir);

        task.run();

        Path descriptor = outputDir.resolve("com/example/generated/public_/tables/Accounts.java");
        assertTrue(Files.exists(descriptor));
        assertFalse(Files.exists(outputDir.resolve(".titan-generate.fingerprint")),
                "homegrown fingerprints are deleted (GAP S8); Gradle owns incrementality");

        Files.delete(descriptor);
        task.run();

        assertTrue(Files.exists(descriptor), "a deleted output must be regenerated by the next run");
    }

    @Test
    void regenerationIsDeterministic() throws Exception {
        Path outputDir = tempDir.resolve("generated-deterministic");
        TitanGenerateTask task = ddlBackedTask(outputDir);

        task.run();
        Path descriptor = outputDir.resolve("com/example/generated/public_/tables/Accounts.java");
        String firstContent = Files.readString(descriptor, StandardCharsets.UTF_8);

        task.run();

        assertEquals(firstContent, Files.readString(descriptor, StandardCharsets.UTF_8),
                "reruns over identical inputs must produce byte-identical outputs");
    }
}
